name: SemEval2024-Task2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - dbus=1.13.6=he372182_0
  - expat=2.2.10=h9c3ff4c_0
  - faiss-cpu=1.7.3=py3.9_h2a577fa_0_cpu
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py39h06a4308_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libfaiss=1.7.3=h2bc3f7f_0_cpu
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - maven=3.9.1=ha770c72_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_1
  - nltk=3.8.1=pyhd8ed1ab_0
  - numexpr=2.8.4=py39he184ba9_0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openjdk=11.0.13=h87a67e3_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.0.1=py39h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch-cuda=11.7=h778d358_3
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0=py39hb9d737c_4
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_1
  - scikit-learn=1.2.2=py39h6a678d5_0
  - sentence-transformers=2.2.2=pyhd8ed1ab_0
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - sympy=1.11.1=py39h06a4308_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.0=py39_cpu
  - torchvision=0.15.0=py39_cpu
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing-extensions=4.4.0=py39h06a4308_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - accelerate==0.25.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - auto-gptq==0.6.0
      - beautifulsoup4==4.12.0
      - bitsandbytes==0.42.0
      - blis==0.7.9
      - cachetools==5.3.2
      - catalogue==2.0.8
      - cbor==1.0.0
      - cbor2==5.4.6
      - cloudpathlib==0.16.0
      - coloredlogs==15.0.1
      - confection==0.0.4
      - cymem==2.0.7
      - cython==0.29.33
      - datasets==2.16.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - einops==0.6.1
      - en-core-web-md==3.7.0
      - flatbuffers==23.3.3
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gekko==1.0.6
      - gitdb==4.0.11
      - gitpython==3.1.41
      - huggingface-hub==0.20.2
      - humanfriendly==10.0
      - ijson==3.2.0.post0
      - ir-datasets==0.5.4
      - langcodes==3.3.0
      - lemminflect==0.2.3
      - lightgbm==3.3.5
      - llvmlite==0.39.1
      - loralib==0.1.2
      - lxml==4.9.2
      - lz4==4.3.2
      - markdown-it-py==2.2.0
      - mdurl==0.1.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.9
      - negate==1.1.3
      - nmslib==2.1.1
      - numba==0.56.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - onnxruntime==1.14.1
      - orjson==3.8.8
      - pandas==1.5.3
      - pathy==0.10.1
      - peft==0.7.1
      - preshed==3.0.8
      - protobuf==4.22.1
      - psutil==5.9.4
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyautocorpus==0.1.9
      - pybind11==2.6.1
      - pydantic==1.10.7
      - pygments==2.14.0
      - pyjnius==1.4.2
      - pyserini==0.20.0
      - pytz==2023.2
      - ranx==0.3.6
      - regex==2023.3.23
      - rich==13.3.3
      - rouge==1.0.1
      - safetensors==0.4.1
      - scipy==1.10.1
      - sentencepiece==0.1.97
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - shtab==1.6.5
      - smart-open==6.3.0
      - smmap==5.0.1
      - soupsieve==2.4
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.6
      - tabulate==0.9.0
      - termcolor==2.4.0
      - thinc==8.1.9
      - tokenizers==0.15.0
      - torch==2.1.2
      - transformers==4.36.2
      - trec-car-tools==2.6
      - triton==2.1.0
      - trl==0.7.9
      - typer==0.7.0
      - tyro==0.6.3
      - unlzw3==0.2.2
      - wandb==0.16.2
      - warc3-wet==0.2.3
      - warc3-wet-clueweb09==0.2.5
      - wasabi==1.1.1
      - weasel==0.3.4
      - xxhash==3.4.1
      - yarl==1.9.4
      - zlib-state==0.1.5
prefix: /cfs/home/u021010/miniconda3/envs/trecIR
